{
 "title": "PROD: MPPT - Brightside",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "MPPT A, B, C, D Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"InputVoltageA\" or r[\"_field\"] == \"InputVoltageB\" or r[\"_field\"] == \"InputVoltageC\" or r[\"_field\"] == \"InputVoltageD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Input Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"InputCurrentA\" or r[\"_field\"] == \"InputCurrentB\" or r[\"_field\"] == \"InputCurrentC\" or r[\"_field\"] == \"InputCurrentD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Output Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputCurrentA\" or r[\"_field\"] == \"OutputCurrentB\" or r[\"_field\"] == \"OutputCurrentC\" or r[\"_field\"] == \"OutputCurrentD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputVoltageA\" or r[\"_field\"] == \"OutputVoltageB\" or r[\"_field\"] == \"OutputVoltageC\" or r[\"_field\"] == \"OutputVoltageD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Mosfet Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MosfetTemperatureA\" or r[\"_field\"] == \"MosfetTemperatureB\" or r[\"_field\"] == \"MosfetTemperatureC\" or r[\"_field\"] == \"MosfetTemperatureD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Controller Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ControllerTemperatureA\" or r[\"_field\"] == \"ControllerTemperatureB\" or r[\"_field\"] == \"ControllerTemperatureC\" or r[\"_field\"] == \"ControllerTemperatureD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Aux 12V",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Aux12VA\" or r[\"_field\"] == \"Aux12VB\" or r[\"_field\"] == \"Aux12VC\" or r[\"_field\"] == \"Aux12VD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Aux 3V",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Aux3VA\" or r[\"_field\"] == \"Aux3VB\" or r[\"_field\"] == \"Aux3VC\" or r[\"_field\"] == \"Aux3VD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Max Output Voltage Limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MaxOutputVoltageLimitA\" or r[\"_field\"] == \"MaxOutputVoltageLimitB\" or r[\"_field\"] == \"MaxOutputVoltageLimitC\" or r[\"_field\"] == \"MaxOutputVoltageLimitD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Max Input Current Limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MaxInputCurrentLimitA\" or r[\"_field\"] == \"MaxInputCurrentLimitB\" or r[\"_field\"] == \"MaxInputCurrentLimitC\" or r[\"_field\"] == \"MaxInputCurrentLimitD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D CAN Tx Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CANTXErrorCounterA\" or r[\"_field\"] == \"CANTXErrorCounterB\" or r[\"_field\"] == \"CANTXErrorCounterC\" or r[\"_field\"] == \"CANTXErrorCounterD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D CAN Rx Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CANRXErrorCounterA\" or r[\"_field\"] == \"CANRXErrorCounterB\" or r[\"_field\"] == \"CANRXErrorCounterC\" or r[\"_field\"] == \"CANRXErrorCounterD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D CAN Tx Overflow Counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CANTXOverflowCounterA\" or r[\"_field\"] == \"CANTXOverflowCounterB\" or r[\"_field\"] == \"CANTXOverflowCounterC\" or r[\"_field\"] == \"CANTXOverflowCounterD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Under Voltage 12V",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Undervoltage12VA\" or r[\"_field\"] == \"Undervoltage12VB\" or r[\"_field\"] == \"Undervoltage12VC\" or r[\"_field\"] == \"Undervoltage12VD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D HW Overcurrent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HWOvercurrentA\" or r[\"_field\"] == \"HWOvercurrentB\" or r[\"_field\"] == \"HWOvercurrentC\" or r[\"_field\"] == \"HWOvercurrentD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D HW Overvoltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HWOvervoltageA\" or r[\"_field\"] == \"HWOvervoltageB\" or r[\"_field\"] == \"HWOvervoltageC\" or r[\"_field\"] == \"HWOvervoltageD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Battery Full",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryFullA\" or r[\"_field\"] == \"BatteryFullB\" or r[\"_field\"] == \"BatteryFullC\" or r[\"_field\"] == \"BatteryFullD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Battery Low",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryLowA\" or r[\"_field\"] == \"BatteryLowB\" or r[\"_field\"] == \"BatteryLowC\" or r[\"_field\"] == \"BatteryLowD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Mosfet Overheat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MosfetOverheatA\" or r[\"_field\"] == \"MosfetOverheatB\" or r[\"_field\"] == \"MosfetOverheatC\" or r[\"_field\"] == \"MosfetOverheatD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Low Array Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"LowArrayPowerA\" or r[\"_field\"] == \"LowArrayPowerB\" or r[\"_field\"] == \"LowArrayPowerC\" or r[\"_field\"] == \"LowArrayPowerD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Global MPPT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GlobalMPPTA\" or r[\"_field\"] == \"GlobalMPPTC\" or r[\"_field\"] == \"GlobalMPPTB\" or r[\"_field\"] == \"GlobalMPPTD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Local MPPT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"LocalMPPTB\" or r[\"_field\"] == \"LocalMPPTC\" or r[\"_field\"] == \"LocalMPPTA\" or r[\"_field\"] == \"LocalMPPTD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Duty Cycle Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"DutyCycleMaxC\" or r[\"_field\"] == \"DutyCycleMaxB\" or r[\"_field\"] == \"DutyCycleMaxA\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Duty Cycle Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"DutyCycleMinA\" or r[\"_field\"] == \"DutyCycleMinB\" or r[\"_field\"] == \"DutyCycleMinC\" or r[\"_field\"] == \"DutyCycleMinD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Mosfet Temp Fault",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MosfetTempFaultA\" or r[\"_field\"] == \"MosfetTempFaultB\" or r[\"_field\"] == \"MosfetTempFaultC\" or r[\"_field\"] == \"MosfetTempFaultD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Output Voltage Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputVoltageMaxA\" or r[\"_field\"] == \"OutputVoltageMaxB\" or r[\"_field\"] == \"OutputVoltageMaxC\" or r[\"_field\"] == \"OutputVoltageMaxD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Input Current Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"InputCurrentMaxA\" or r[\"_field\"] == \"InputCurrentMaxC\" or r[\"_field\"] == \"InputCurrentMaxB\" or r[\"_field\"] == \"InputCurrentMaxD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Input Current Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"InputCurrentMinA\" or r[\"_field\"] == \"InputCurrentMinB\" or r[\"_field\"] == \"InputCurrentMinC\" or r[\"_field\"] == \"InputCurrentMinD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Mode",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ModeC\" or r[\"_field\"] == \"ModeB\" or r[\"_field\"] == \"ModeA\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Test Counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TestCounterA\" or r[\"_field\"] == \"TestCounterB\" or r[\"_field\"] == \"TestCounterC\" or r[\"_field\"] == \"TestCounterD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Output Voltage Battery Side of Fuse",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OutputVoltageBattSideA\" or r[\"_field\"] == \"OutputVoltageBattSideB\" or r[\"_field\"] == \"OutputVoltageBattSideC\" or r[\"_field\"] == \"OutputVoltageBattSideD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Connector Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ConnectorTemperatureA\" or r[\"_field\"] == \"ConnectorTemperatureB\" or r[\"_field\"] == \"ConnectorTemperatureC\" or r[\"_field\"] == \"ConnectorTemperatureD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Mode Command",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ModeCmdA\" or r[\"_field\"] == \"ModeCmdB\" or r[\"_field\"] == \"ModeCmdC\" or r[\"_field\"] == \"ModeCmdD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Max Output Current Command",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MaxOutputCurrentCmdA\" or r[\"_field\"] == \"MaxOutputCurrentCmdC\" or r[\"_field\"] == \"MaxOutputCurrentCmdB\" or r[\"_field\"] == \"MaxOutputCurrentCmdD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "MPPT A, B, C, D Max Output Voltage Command",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MPPT\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MaxOutputVoltageCmdA\" or r[\"_field\"] == \"MaxOutputVoltageCmdB\" or r[\"_field\"] == \"MaxOutputVoltageCmdC\" or r[\"_field\"] == \"MaxOutputVoltageCmdD\")\n  |> aggregateWindow(every: 1ms, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}