{
 "title": "PROD: BMS - Cascadia",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "MST Tick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BmsHeartbeatCounter\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "HVC time since heartbeat",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HVC\")\n  |> filter(fn: (r) => r[\"car\"] == \"Brightside\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HVCTimeSinceBootUp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Supp voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HVC\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SuppVoltage\")\n  |> filter(fn: (r) => r[\"car\"] == \"Brightside\")\n  |> filter(fn: (r) => r[\"class\"] == \"HvcSuppVoltage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Shunt Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HVC\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PackCurrent\")\n  |> filter(fn: (r) => r[\"car\"] == \"Brightside\")\n  |> filter(fn: (r) => r[\"class\"] == \"HVCShuntCurrent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Module 0-15",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Mod0Voltage\" or r[\"_field\"] == \"Mod1Voltage\" or r[\"_field\"] == \"Mod2Voltage\" or r[\"_field\"] == \"Mod3Voltage\" or r[\"_field\"] == \"Mod4Voltage\" or r[\"_field\"] == \"Mod5Voltage\" or r[\"_field\"] == \"Mod6Voltage\" or r[\"_field\"] == \"Mod7Voltage\" or r[\"_field\"] == \"Mod8Voltage\" or r[\"_field\"] == \"Mod9Voltage\" or r[\"_field\"] == \"Mod10Voltage\" or r[\"_field\"] == \"Mod11Voltage\" or r[\"_field\"] == \"Mod12Voltage\" or r[\"_field\"] == \"Mod13Voltage\" or r[\"_field\"] == \"Mod14Voltage\" or r[\"_field\"] == \"Mod15Voltage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Module 16-31",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Mod16Voltage\" or r[\"_field\"] == \"Mod17Voltage\" or r[\"_field\"] == \"Mod18Voltage\" or r[\"_field\"] == \"Mod19Voltage\" or r[\"_field\"] == \"Mod20Voltage\" or r[\"_field\"] == \"Mod21Voltage\" or r[\"_field\"] == \"Mod22Voltage\" or r[\"_field\"] == \"Mod23Voltage\" or r[\"_field\"] == \"Mod24Voltage\" or r[\"_field\"] == \"Mod25Voltage\" or r[\"_field\"] == \"Mod26Voltage\" or r[\"_field\"] == \"Mod27Voltage\" or r[\"_field\"] == \"Mod28Voltage\" or r[\"_field\"] == \"Mod29Voltage\" or r[\"_field\"] == \"Mod30Voltage\" or r[\"_field\"] == \"Mod31Voltage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MST Faults",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ErrCommFail\" or r[\"_field\"] == \"ErrSelfTest\" or r[\"_field\"] == \"FaultOverTemp\" or r[\"_field\"] == \"FaultOverVolt\" or r[\"_field\"] == \"FaultUnderTemp\" or r[\"_field\"] == \"FaultUnderVolt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Balancing active and enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BalancingActive\" or r[\"_field\"] == \"BalancingEnable\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Module thats balancing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BalanceBitmap\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "HVC State",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HVC\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HVCState\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Module thats balancing",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BalanceBitmap\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "HVC State",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HVC\")\n  |> filter(fn: (r) => r[\"_field\"] == \"HVCState\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MDI Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DIST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MDICurrent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Module's with Max and Min temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MaxTempModuleIdx\" or r[\"_field\"] == \"MinTempModuleIdx\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Average Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"AvgTemp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Module 17-32 Temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Mod17Temp\" or r[\"_field\"] == \"Mod18Temp\" or r[\"_field\"] == \"Mod19Temp\" or r[\"_field\"] == \"Mod20Temp\" or r[\"_field\"] == \"Mod21Temp\" or r[\"_field\"] == \"Mod22Temp\" or r[\"_field\"] == \"Mod23Temp\" or r[\"_field\"] == \"Mod24Temp\" or r[\"_field\"] == \"Mod25Temp\" or r[\"_field\"] == \"Mod26Temp\" or r[\"_field\"] == \"Mod27Temp\" or r[\"_field\"] == \"Mod28Temp\" or r[\"_field\"] == \"Mod29Temp\" or r[\"_field\"] == \"Mod30Temp\" or r[\"_field\"] == \"Mod31Temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "DIST Currents",
   "type": "stat",
   "description": "eFuse currents 5 lsb",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DIST\")\n  |> filter(fn: (r) => r[\"_field\"] == \"DRDCurrent\" or r[\"_field\"] == \"MDICurrent\" or r[\"_field\"] == \"SpareControlCurrent\" or r[\"_field\"] == \"SpareCurrent\" or r[\"_field\"] == \"SpareMuxCurrent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "HVC Fault",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CAN_prod\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HVC\")\n  |> filter(fn: (r) => r[\"_field\"] == \"DcdcFault\" or r[\"_field\"] == \"DistFaultFlag\" or r[\"_field\"] == \"EstopFault\" or r[\"_field\"] == \"ImdFault\" or r[\"_field\"] == \"MasterboardFault\" or r[\"_field\"] == \"OvercurrentFault\" or r[\"_field\"] == \"UndercurrentFault\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}