# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import canlink_pb2 as canlink__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in canlink_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CanIngestStub(object):
    """Streaming: the client (RPi) sends successive FrameBatch messages,
    server returns one UploadAck when the stream completes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFrames = channel.stream_unary(
                '/canlink.CanIngest/UploadFrames',
                request_serializer=canlink__pb2.FrameBatch.SerializeToString,
                response_deserializer=canlink__pb2.UploadAck.FromString,
                _registered_method=True)


class CanIngestServicer(object):
    """Streaming: the client (RPi) sends successive FrameBatch messages,
    server returns one UploadAck when the stream completes.
    """

    def UploadFrames(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CanIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFrames': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFrames,
                    request_deserializer=canlink__pb2.FrameBatch.FromString,
                    response_serializer=canlink__pb2.UploadAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'canlink.CanIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('canlink.CanIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CanIngest(object):
    """Streaming: the client (RPi) sends successive FrameBatch messages,
    server returns one UploadAck when the stream completes.
    """

    @staticmethod
    def UploadFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/canlink.CanIngest/UploadFrames',
            canlink__pb2.FrameBatch.SerializeToString,
            canlink__pb2.UploadAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
