# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: canlink.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'canlink.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcanlink.proto\x12\x07\x63\x61nlink\"`\n\x08RawFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0e\n\x06\x63\x61n_id\x18\x02 \x01(\r\x12\x16\n\x0eis_extended_id\x18\x03 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x0b\n\x03\x64lc\x18\x05 \x01(\r\"/\n\nFrameBatch\x12!\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x11.canlink.RawFrame\"$\n\tUploadAck\x12\x17\n\x0f\x66rames_ingested\x18\x01 \x01(\x04\x32\x46\n\tCanIngest\x12\x39\n\x0cUploadFrames\x12\x13.canlink.FrameBatch\x1a\x12.canlink.UploadAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'canlink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWFRAME']._serialized_start=26
  _globals['_RAWFRAME']._serialized_end=122
  _globals['_FRAMEBATCH']._serialized_start=124
  _globals['_FRAMEBATCH']._serialized_end=171
  _globals['_UPLOADACK']._serialized_start=173
  _globals['_UPLOADACK']._serialized_end=209
  _globals['_CANINGEST']._serialized_start=211
  _globals['_CANINGEST']._serialized_end=281
# @@protoc_insertion_point(module_scope)
